"use client";

import { Download, Printer } from "lucide-react";
import { jsPDF } from "jspdf";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { ptBRNumber } from "@/lib/utils";

type MetricRow = { indicator_name: string; value: string | number | null; kind: string };
type ScaleRow = { scale_type: string; moment: string; total: number; improved: boolean | null };
const scaleNames: Record<string, string> = { barthel: "Barthel", mrc: "MRC", melhoria_uti: "Melhoria UTI" };

export function ReportsView({ month, metrics, scales }: { month: string; metrics: MetricRow[]; scales: ScaleRow[] }) {
  const totals = new Map<string, number>(); metrics.forEach((x) => totals.set(x.indicator_name, (totals.get(x.indicator_name) ?? 0) + Number(x.value ?? 0)));
  const rows = [...totals].sort((a, b) => b[1] - a[1]);
  const scaleRows = Object.keys(scaleNames).map((type) => { const exits = scales.filter((x) => x.scale_type === type && x.moment === "saida" && x.improved !== null); const improved = exits.filter((x) => x.improved).length; return { name: scaleNames[type], assessments: scales.filter((x) => x.scale_type === type).length, exits: exits.length, improved, rate: exits.length ? improved / exits.length * 100 : 0 }; });
  function pdf() { const doc = new jsPDF(); doc.setFontSize(18); doc.text("MaisFisio — Relatório mensal", 16, 20); doc.setFontSize(11); doc.text(`Competência: ${month.split("-").reverse().join("/")}`, 16, 29); let y = 42; doc.setFontSize(13); doc.text("Produção assistencial", 16, y); y += 8; doc.setFontSize(9); rows.slice(0, 35).forEach(([name, value]) => { doc.text(name.slice(0, 78), 16, y); doc.text(ptBRNumber.format(value), 190, y, { align: "right" }); y += 6; if (y > 275) { doc.addPage(); y = 20; } }); y += 7; doc.setFontSize(13); doc.text("Escalas clínicas", 16, y); y += 8; doc.setFontSize(9); scaleRows.forEach((x) => { doc.text(`${x.name}: ${x.assessments} avaliações · ${ptBRNumber.format(x.rate)}% de melhora`, 16, y); y += 6; }); doc.save(`maisfisio-relatorio-${month}.pdf`); }
  return <div className="grid gap-6"><header className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h1 className="page-title">Relatórios mensais</h1><p className="page-description">Consolidado pronto para impressão e compartilhamento.</p></div><div className="no-print flex gap-2"><Button variant="outline" onClick={() => window.print()}><Printer className="size-4" />Imprimir</Button><Button onClick={pdf}><Download className="size-4" />Gerar PDF</Button></div></header><Card className="no-print"><CardContent className="pt-5 md:pt-6"><form className="flex flex-col items-end gap-3 sm:flex-row"><div className="field w-full sm:max-w-xs"><label className="text-sm font-medium">Competência</label><Input type="month" name="mes" defaultValue={month} /></div><Button type="submit">Carregar relatório</Button></form></CardContent></Card><div className="grid gap-6 xl:grid-cols-2"><Card className="print-card"><CardHeader><CardTitle>Produção assistencial</CardTitle><CardDescription>{rows.length} indicadores com registro em {month.split("-").reverse().join("/")}</CardDescription></CardHeader><CardContent className="divide-y p-0">{rows.map(([name, value]) => <div key={name} className="flex items-center justify-between gap-5 px-5 py-3 md:px-6"><span className="text-sm">{name}</span><strong className="font-display">{ptBRNumber.format(value)}</strong></div>)}{!rows.length && <p className="p-6 text-sm text-muted-foreground">Sem produção no mês.</p>}</CardContent></Card><Card className="print-card h-fit"><CardHeader><CardTitle>Escalas clínicas</CardTitle><CardDescription>Evolução entre entrada e saída.</CardDescription></CardHeader><CardContent className="space-y-5">{scaleRows.map((x) => <div key={x.name} className="rounded-xl bg-muted/60 p-4"><div className="flex justify-between"><strong>{x.name}</strong><strong className="text-primary">{ptBRNumber.format(x.rate)}%</strong></div><p className="mt-1 text-xs text-muted-foreground">{x.assessments} avaliações · {x.improved} de {x.exits} saídas com melhora</p></div>)}</CardContent></Card></div></div>;
}
